/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'stas' at '8/3/15 10:59 PM' with Gradle 2.5
 *
 * @author stas, @date 8/3/15 10:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
